## BUILD

FROM golang:buster AS build

WORKDIR /app
COPY go.mod ./
COPY go.sum ./

RUN go mod download
COPY *.go ./
RUN go build -o /list-service-build

EXPOSE 4000

CMD [ "/list-service-build" ]


## DEPLOY

FROM gcr.io/distroless/base-debian10
WORKDIR /
COPY --from=build /list-service-build /list-service-build

# Copy config file and set ENV CONFIG_PATH to point to it
COPY service.json ./
ENV CONFIG_PATH=/service.json

EXPOSE 4000
USER nonroot:nonroot

ENTRYPOINT [ "/list-service-build" ]


